# Generated by Django 3.2 on 2022-01-01 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('captaincook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredients',
            name='recipe_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='captaincook.recipe'),
            preserve_default=False,
        ),
    ]
