# Generated by Django 3.2 on 2022-01-08 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captaincook', '0002_recipeingredients_recipe_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_image_url',
            field=models.URLField(),
        ),
    ]
