# Generated by Django 3.2 on 2022-01-09 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captaincook', '0003_alter_recipe_recipe_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_image_url',
            field=models.URLField(max_length=500),
        ),
    ]
