# Generated by Django 3.2 on 2022-01-09 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captaincook', '0004_alter_recipe_recipe_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_image_url',
            field=models.CharField(default='https://good-food.ro/wp-content/uploads/2020/03/GoodFood-LOGO-300x283px.png', max_length=500),
        ),
    ]
